# Generated by Django 2.0.2 on 2018-02-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180224_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='time_slot',
        ),
    ]
