# Generated by Django 2.0.2 on 2018-02-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_seat_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='time_slot',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='api.TimeSlot'),
        ),
    ]
