# Generated by Django 2.0.2 on 2018-02-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180224_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_to_student',
        ),
    ]
