# Generated by Django 2.0.2 on 2018-03-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180225_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.TimeSlotStatus'),
        ),
    ]
