# Generated by Django 2.0.2 on 2018-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180311_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timeZone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
