# Generated by Django 2.0.2 on 2018-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180421_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
